name: 📝 Suggest Config Tip
description: Have a great tip for developers?
title: "[New Tip]: "
labels: ["tip", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a tip to share with fellow developers? We accept PRs! But we're happy to take a suggestion.
  - type: input
    id: kind
    attributes:
      label: What is the name of the config kind?
      description: This config kind should already exist in `src/content/configKinds`
      placeholder: ex. package.json
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: Config Tip
      description: Share your developer config tip!
      placeholder: |
        {
          "name": "my-package",
          "version": "1.0.0",
          "description": "My package",
          "main": "index.js",
          "scripts": {
            "test": "echo \"Error: no test specified\" && exit 1"
          },
          "keywords": [],
          "author": "",
          "license": "ISC"
        }
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Give us a short description of the config kind
      description: Keept the description between 100 and 160 characters
      placeholder: ex. This really cool tip will help you do X, Y, and Z.
    validations:
      required: false
  - type: textarea
    id: body-text
    attributes:
      label: Body Area
      description: You can use markdown here to write the body of the post
      placeholder: |
        ex. This really cool tip will help you do X, Y, and Z.
    validations:
      required: false
  - type: textarea
    id: more
    attributes:
      label: Anything Else?
      description: Anything else you want to share?
      placeholder: More details...
    validations:
      required: false